### ISSUE TITLE
Not appear in dashboard

### ISSUE THREAD

**Issue by noobi97** [philthynz/zabbix-mssql-2008-2012-powershell#2]
Hi, 

Thanks for this amazing stuff! But i got a problem. When i would like appearing any metric in dashboard it's not work :S 
Left side is classic graph, right side is dashboard graph without data. (connected users)
![Screenshot 2019-11-20 at 9 49 16](https://user-images.githubusercontent.com/12101834/69223318-6e70f180-0b7b-11ea-9c17-f30365927e1f.png)

**Comment by philthynz** [comment]
Hey man.

Yea I have the same problems. Those metrics don't map on a dashboard, not sure why. So I've added a graph to each host. Unfortunately that can't be done via a template because the metrics have to be discovered fist.

So on the host, create a graph:
![image](https://user-images.githubusercontent.com/17504095/69286488-41ded780-0c58-11ea-8513-9c6a0699453b.png)

And then add a Simple Graph to the dashboard. Mine looks like this:
![image](https://user-images.githubusercontent.com/17504095/69286683-bc0f5c00-0c58-11ea-9ff0-8024b89953d2.png)
